// Vue/vue-base/src/App2.vue
<script setup>
import { onBeforeMount, onMounted, ref } from 'vue'

const h2Ref = ref()

onBeforeMount(() => {
  console.log('App2 onBeforeMount', h2Ref.value)
})
onMounted(() => {
  console.log('App2 onMounted', h2Ref.value)
})
</script>

<template>
  <h2 ref="h2Ref">hello</h2>
</template>

<style scoped>

</style>

// react/control/src/App2.jsx
import React from 'react'

function App2 () {

  const [value, setValue] = React.useState('hello')

  function onChange (event) {
    console.log(event.target.value)
    setValue(event.target.value.toUpperCase())
  }

  return (
    <input type="text" value={value} onChange={onChange}/>
  )
}

export default App2
